import React, { useMemo, useState } from 'react';
import { Transaction } from '../../../interfaces/Transaction';
import { ColumnDef } from '@tanstack/react-table';
import DataTable from '../../../components/DataTable/DataTable';

function HomeDashboardRecentTransactions() {
    const columns: ColumnDef<Transaction>[] = [
        {
            header: 'Account',
            accessorKey: 'account_id',
        },
        {
            header: 'Date',
            accessorKey: 'date',
            cell: ({ row }) => {
                const date: Date = row.getValue('date');
                const formattedDate = new Date(date).toLocaleDateString();
                return formattedDate;
            },
        },
        {
            header: 'Amount',
            accessorKey: 'amount',
        },
        {
            header: 'Company Name',
            accessorKey: 'name',
        },
        {
            header: 'Payment Channel',
            accessorKey: 'payment_channel',
        },
        {
            header: 'Category',
            accessorKey: 'primary_category',
        },
        {
            header: 'Sub-Category',
            accessorKey: 'detailed_category',
        },
    ];

    const [recentTransactionsData, setRecentTransactionData] = useState<Transaction[]>([
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
        {
            id: '1',
            account_id: '325',
            transaction_id: '5meQXqWV5VCBqlm3x3kJtjLBM51n4BFGVQK9B',
            amount: -500.0,
            date: new Date('2023-03-29'),
            name: 'United Airlines',
            payment_channel: 'in store',
            primary_category: 'Travel',
            detailed_category: 'Airlines and Aviation Services',
        },
        {
            id: '2',
            account_id: '325',
            transaction_id: 'JDlryo3bVbf7GxmzXzM8SQW361PnE3sQje69R',
            amount: 12.0,
            date: new Date('2023-03-28'),
            name: "McDonald's",
            payment_channel: 'in store',
            primary_category: 'Food and Drink',
            detailed_category: 'Restaurants',
        },
    ]);

    const memoData = useMemo(() => recentTransactionsData, []);

    return (
        <div
            id='home-dashboard-recent-transactions'
            className='mb-2 ml-2 w-[60%] flex-1 overflow-scroll rounded-sm border border-textColor-primary bg-backgroundColor-primary'
        >
            <strong className='p-1 font-medium text-textColor-secondary'>
                Recent Transactions
            </strong>
            <div className='m-3 w-[90%]'>
                <DataTable columns={columns} data={memoData} />
            </div>
        </div>
    );
}

export default HomeDashboardRecentTransactions;
